<?php
return [
    [
        'exam_code' => '2023_aki_4',
        'question_number' => 1,
        'sub_question_number' => 1,
        'small_question_number' => 1,
        'text' => '10,11,12,13',
    ],
    [
        'exam_code' => '2023_aki_4',
        'question_number' => 1,
        'sub_question_number' => 1,
        'small_question_number' => 2,
        'text' => '大',
    ],
    [
        'exam_code' => '2023_aki_4',
        'question_number' => 1,
        'sub_question_number' => 1,
        'small_question_number' => 3,
        'text' => 'C',
    ],
    [
        'exam_code' => '2023_aki_4',
        'question_number' => 2,
        'sub_question_number' => 1,
        'text' => 'G百貨店で,Sサービスへログイン可能なIPアドレスをW社プロキシだけに設定する。',
    ],
    [
        'exam_code' => '2023_aki_4',
        'question_number' => 2,
        'sub_question_number' => 2,
        'small_question_number' => 1,
        'text' => '配送管理課員が,添付ファイルを開き,配送管理用PCが未知のマルウェアに感染した結果,IDとPWを周知するメールが読み取られ,SサービスのIDとPWが窃取される。そのIDとPWが利用されて,W社外からSサービスにログインされて,Z情報が漏えいする。',
    ],
    [
        'exam_code' => '2023_aki_4',
        'question_number' => 2,
        'sub_question_number' => 2,
        'small_question_number' => 2,
        'text' => '2,3,5,6,9,12',
    ],
    [
        'exam_code' => '2023_aki_4',
        'question_number' => 2,
        'sub_question_number' => 2,
        'small_question_number' => 3,
        'text' => '大',
    ],
    [
        'exam_code' => '2023_aki_4',
        'question_number' => 2,
        'sub_question_number' => 2,
        'small_question_number' => 4,
        'text' => '高',
    ],
    [
        'exam_code' => '2023_aki_4',
        'question_number' => 2,
        'sub_question_number' => 2,
        'small_question_number' => 5,
        'text' => 'A',
    ],
    [
        'exam_code' => '2023_aki_4',
        'question_number' => 2,
        'sub_question_number' => 2,
        'small_question_number' => 6,
        'text' => '配送管理用PCにEDRを導入し,不審な動作が起きていないかを監視する。',
    ],
    [
        'exam_code' => '2023_aki_4',
        'question_number' => 3,
        'sub_question_number' => 1,
        'small_question_number' => 1,
        'text' => '5,10,12',
    ],
    [
        'exam_code' => '2023_aki_4',
        'question_number' => 3,
        'sub_question_number' => 1,
        'small_question_number' => 2,
        'text' => '2,3,4',
    ],
];
