# Laravel11はphp8.2以上
FROM php:8.3-fpm

# Composer install
COPY --from=composer:2.2 /usr/bin/composer /usr/bin/composer

# install Node.js
COPY --from=node:20.5 /usr/local/bin /usr/local/bin
COPY --from=node:20.5 /usr/local/lib /usr/local/lib

# npmのアップデート
RUN npm install -g npm@10.8.0

RUN apt-get update && \
  # --no-install-recommendで不要なパッケージのインストールを防止
  apt-get -y install --no-install-recommends git zip unzip vim libzip-dev libicu-dev libonig-dev cron mariadb-client && \
  # 以下2行でパッケージインストールで使用したキャッシュファイルを削除
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  # PHPの拡張ライブラリをインストール
  docker-php-ext-install intl pdo_mysql bcmath zip

# xdebug
RUN pecl install xdebug \
  && docker-php-ext-enable xdebug

COPY ./docker/php/php.ini /usr/local/etc/php/php.ini
COPY ./docker/php/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

WORKDIR /var/www/html
