services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    volumes:
      - ./src:/var/www/html
    ports:
      - ${IP}:5173:5173 # Vite HMR
    expose:
      - "9000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Tokyo
    depends_on:
      - db

  web:
    image: caddy:2
    ports:
      - ${IP}:80:80
    volumes:
      - ./docker/caddy/Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - ./src:/var/www/html:ro
    depends_on:
      - app

  db:
    image: mysql:8.4
    ports:
      - ${IP}:3306:3306
    volumes:
      - db-volumes:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/z-my.cnf:ro
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - TZ=Asia/Tokyo

  db-testing:
    image: mysql:8.4
    volumes:
      - db-volumes:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/z-my.cnf:ro
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - TZ=Asia/Tokyo

volumes:
  db-volumes:
