<?php
return [
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 4,
        'question_number' => 1,
        'sub_question_number' => 1,
        'small_question_number' => 1,
        'type' => 'checkbox',
        'text' => <<<EOF
表4及び表5中の[空欄 ア] 〜 [空欄 エ]に入れる適切な字句を答えよ。
[空欄 ア]は,表2中から該当する項番を全て選び,数字で答えよ。該当する項番がない場合は,"なし” と答えよ。
EOF,
        'options' => json_encode([
            ['label' => '1', 'value' => '1'],
            ['label' => '2', 'value' => '2'],
            ['label' => '3', 'value' => '3'],
            ['label' => '4', 'value' => '4'],
            ['label' => '5', 'value' => '5'],
            ['label' => '6', 'value' => '6'],
            ['label' => '7', 'value' => '7'],
            ['label' => '8', 'value' => '8'],
            ['label' => '9', 'value' => '9'],
            ['label' => '10', 'value' => '10'],
            ['label' => '11', 'value' => '11'],
            ['label' => '12', 'value' => '12'],
            ['label' => '13', 'value' => '13'],
            ['label' => 'なし', 'value' => 'なし'],
        ]),
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 4,
        'question_number' => 1,
        'sub_question_number' => 1,
        'small_question_number' => 2,
        'type' => 'radio',
        'text' => "[空欄 イ]は答案用紙の大・中・小のいずれかの文字を○で囲んで示せ。",
        'options' => json_encode([
            ['label' => '大', 'value' => '大'],
            ['label' => '中', 'value' => '中'],
            ['label' => '小', 'value' => '小'],
        ]),
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 4,
        'question_number' => 1,
        'sub_question_number' => 1,
        'small_question_number' => 3,
        'type' => 'radio',
        'text' => "[空欄 ウ]は答案用紙のA・B・C・D のいずれかの文字を○で囲んで示せ。",
        'options' => json_encode([
            ['label' => 'A', 'value' => 'A'],
            ['label' => 'B', 'value' => 'B'],
            ['label' => 'C', 'value' => 'C'],
            ['label' => 'D', 'value' => 'D'],
        ]),
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 4,
        'question_number' => 2,
        'sub_question_number' => 1,
        'type' => 'textarea',
        'text' => <<<EOF
次の問いに答えよ。
(1) 表4中の[空欄 あ]に入れる適切な字句を,本文に示した状況設定に沿う範囲で,あなたの知見に基づき,答えよ。
EOF,
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 4,
        'question_number' => 2,
        'sub_question_number' => 2,
        'small_question_number' => 1,
        'type' => 'input',
        'text' => <<<EOF
(2) 解答した[空欄 あ]の内容に基づき,表4及び表5中の[空欄 い]〜[空欄 き]に入れる適切な字句を答えよ。
[空欄 う]は,表2中から該当する項番を全て選び,数字で答えよ。該当する項番がない場合は,“なし”と答えよ。
[空欄 え]は答案用紙の大・中・小のいずれかの文字を○で囲んで示せ。
[空欄 お]は答案用紙の高・中・低のいずれかの文字を○で囲んで示せ。
[空欄 か]は答案用紙のA・B・C・D のいずれかの文字を○で囲んで示せ。
EOF,
        'options' => json_encode([
            ['label' => '[空欄 い]', 'value' => 'い'],
        ]),
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 4,
        'question_number' => 2,
        'sub_question_number' => 2,
        'small_question_number' => 2,
        'type' => 'checkbox',
        'text' => "[空欄 う]",
        'options' => json_encode([
            ['label' => '1', 'value' => '1'],
            ['label' => '2', 'value' => '2'],
            ['label' => '3', 'value' => '3'],
            ['label' => '4', 'value' => '4'],
            ['label' => '5', 'value' => '5'],
            ['label' => '6', 'value' => '6'],
            ['label' => '7', 'value' => '7'],
            ['label' => '8', 'value' => '8'],
            ['label' => '9', 'value' => '9'],
            ['label' => '10', 'value' => '10'],
            ['label' => '11', 'value' => '11'],
            ['label' => '12', 'value' => '12'],
            ['label' => '13', 'value' => '13'],
            ['label' => 'なし', 'value' => 'なし'],
        ]),
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 4,
        'question_number' => 2,
        'sub_question_number' => 2,
        'small_question_number' => 3,
        'type' => 'radio',
        'text' => "[空欄 え]",
        'options' => json_encode([
            ['label' => '大', 'value' => '大'],
            ['label' => '中', 'value' => '中'],
            ['label' => '小', 'value' => '小'],
        ]),
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 4,
        'question_number' => 2,
        'sub_question_number' => 2,
        'small_question_number' => 4,
        'type' => 'radio',
        'text' => "[空欄 お]",
        'options' => json_encode([
            ['label' => '高', 'value' => '高'],
            ['label' => '中', 'value' => '中'],
            ['label' => '低', 'value' => '低'],
        ]),
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 4,
        'question_number' => 2,
        'sub_question_number' => 2,
        'small_question_number' => 5,
        'type' => 'radio',
        'text' => "[空欄 か]",
        'options' => json_encode([
            ['label' => 'A', 'value' => 'A'],
            ['label' => 'B', 'value' => 'B'],
            ['label' => 'C', 'value' => 'C'],
            ['label' => 'D', 'value' => 'D'],
        ]),
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 4,
        'question_number' => 2,
        'sub_question_number' => 2,
        'small_question_number' => 6,
        'type' => 'input',
        'text' => "[空欄 き]",
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 4,
        'question_number' => 3,
        'sub_question_number' => 1,
        'small_question_number' => 1,
        'type' => 'checkbox',
        'text' => <<<EOF
表4中の[空欄 a],[空欄 b]に入れる適切な字句について,表2中から該当する項番を全て選び,数字で答えよ。該当する項番がない場合は,“なし”と答えよ。
[空欄 a]
EOF,
        'options' => json_encode([
            ['label' => '1', 'value' => '1'],
            ['label' => '2', 'value' => '2'],
            ['label' => '3', 'value' => '3'],
            ['label' => '4', 'value' => '4'],
            ['label' => '5', 'value' => '5'],
            ['label' => '6', 'value' => '6'],
            ['label' => '7', 'value' => '7'],
            ['label' => '8', 'value' => '8'],
            ['label' => '9', 'value' => '9'],
            ['label' => '10', 'value' => '10'],
            ['label' => '11', 'value' => '11'],
            ['label' => '12', 'value' => '12'],
            ['label' => '13', 'value' => '13'],
            ['label' => 'なし', 'value' => 'なし'],
        ]),
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 4,
        'question_number' => 3,
        'sub_question_number' => 1,
        'small_question_number' => 2,
        'type' => 'checkbox',
        'text' => "[空欄 b]",
        'options' => json_encode([
            ['label' => '1', 'value' => '1'],
            ['label' => '2', 'value' => '2'],
            ['label' => '3', 'value' => '3'],
            ['label' => '4', 'value' => '4'],
            ['label' => '5', 'value' => '5'],
            ['label' => '6', 'value' => '6'],
            ['label' => '7', 'value' => '7'],
            ['label' => '8', 'value' => '8'],
            ['label' => '9', 'value' => '9'],
            ['label' => '10', 'value' => '10'],
            ['label' => '11', 'value' => '11'],
            ['label' => '12', 'value' => '12'],
            ['label' => '13', 'value' => '13'],
            ['label' => 'なし', 'value' => 'なし'],
        ]),
    ],
];
