<?php
return [
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 3,
        'question_number' => 1,
        'sub_question_number' => 1,
        'text' => "ウ,エ",
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 3,
        'question_number' => 2,
        'sub_question_number' => 1,
        'text' => "偽サイトに入力されたTOTPを入手し,そのTOTPが有効な間にログインした。",
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 3,
        'question_number' => 2,
        'sub_question_number' => 2,
        'text' => "ア",
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 3,
        'question_number' => 2,
        'sub_question_number' => 3,
        'text' => "イ",
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 3,
        'question_number' => 2,
        'sub_question_number' => 4,
        'text' => "/procファイルシステムから環境変数を読み取った。",
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 3,
        'question_number' => 2,
        'sub_question_number' => 5,
        'text' => "認証に用いる情報に含まれるオリジン及び署名をサーバが確認する仕組み",
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 3,
        'question_number' => 2,
        'sub_question_number' => 6,
        'text' => "ア",
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 3,
        'question_number' => 3,
        'sub_question_number' => 1,
        'text' => "有効なコード署名が付与された偽のPアプリをJストアにアップロードする攻撃",
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 3,
        'question_number' => 3,
        'sub_question_number' => 2,
        'text' => "J社のWebサイトから削除する。",
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 3,
        'question_number' => 3,
        'sub_question_number' => 3,
        'text' => "秘密鍵が漏れないという利点",
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 3,
        'question_number' => 3,
        'sub_question_number' => 4,
        'small_question_number' => 1,
        'text' => "Pアプリを起動できない。",
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 3,
        'question_number' => 3,
        'sub_question_number' => 4,
        'small_question_number' => 2,
        'text' => "Pアプリをアップデートする。",
    ],
];
