<?php

// 令和5年秋問2
return [
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 2,
        'question_number' => 1,
        'sub_question_number' => 1,
        'small_question_number' => 1,
        'text' => '利用者ID',
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 2,
        'question_number' => 1,
        'sub_question_number' => 1,
        'small_question_number' => 2,
        'text' => 'パスワード',
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 2,
        'question_number' => 1,
        'sub_question_number' => 2,
        'small_question_number' => 1,
        'text' => 'このサーバ証明書は,信頼された認証局から発行されたサーバ証明書ではない',
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 2,
        'question_number' => 1,
        'sub_question_number' => 2,
        'small_question_number' => 2,
        'text' => 'このサーバ証明書に記載されているサーバ名は,接続先のサーバ名と異なる',
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 2,
        'question_number' => 1,
        'sub_question_number' => 3,
        'text' => 'HTTPのアクセスをHTTPSのアクセスに置き換えてアクセスする。その後,偽サイトからサーバ証明書を受け取る。',
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 2,
        'question_number' => 2,
        'sub_question_number' => 1,
        'text' => '外部共有者のメールアドレスに自身の私用メールアドレスを指定する。',
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 2,
        'question_number' => 2,
        'sub_question_number' => 2,
        'text' => 'MACアドレス',
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 2,
        'question_number' => 3,
        'sub_question_number' => 1,
        'text' => 'RADIUS',
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 2,
        'question_number' => 3,
        'sub_question_number' => 2,
        'text' => '秘密鍵',
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 2,
        'question_number' => 3,
        'sub_question_number' => 3,
        'text' => '業務PCから取り出せないように',
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 2,
        'question_number' => 3,
        'sub_question_number' => 4,
        'text' => 'EAP-TLSに必要な認証情報は,業務PCにしか格納できないから',
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 2,
        'question_number' => 3,
        'sub_question_number' => 5,
        'text' => '来客用無線LANからインターネットにアクセスする場合の送信元IPアドレスを a1.b1.c1.d1 とは別のIPアドレスにする。',
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 2,
        'question_number' => 3,
        'sub_question_number' => 6,
        'text' => 'DNS',
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 2,
        'question_number' => 3,
        'sub_question_number' => 7,
        'small_question_number' => 1,
        'text' => '1',
    ],
    [
        'year' => 2023,
        'season' => 'aki',
        'section' => 2,
        'question_number' => 3,
        'sub_question_number' => 7,
        'small_question_number' => 2,
        'text' => '1, 4',
    ],
];
