@startuml 図1 M社のネットワーク構成
skinparam defaultFontName Arial
skinparam componentStyle rectangle

(Bサービス) -- (インターネット)

package "M社" {
    package "執務室" {
        component FW {
            port "WAN-IF1"
            port IF1
        }

        component L2SW {
            port P9
            port P10
            port P11
            port P12
            port P13
            port P20
            port P21
            port P22
            port P23
            port P24
        }
        
        P10 -- [業務サーバ]
        P11 -- [DHCPサーバ]
        P12 -- [DNSサーバ]
        P13 -- [ディレクトリサーバ]

        P20 -- [AP-1]
        P21 -- [AP-2]
        P22 -- [AP-3]
        P23 -- [AP-4]
        [執務室の業務PC]
        執務室の業務PC .. "AP-1": 無線接続
        執務室の業務PC .. "AP-2": 無線接続
        執務室の業務PC .. "AP-3": 無線接続
        執務室の業務PC .. "AP-4": 無線接続

        インターネット -- "WAN-IF1"
        IF1 -- P9

    }
  
    package "会議室" {
            [AP-5] .. [会議室の業務PC群1]: 無線接続
            [AP-5] .. [会議室の業務PC群2]: 無線接続
            [来客持込端末]
            [プロジェクター]

    }
        
    P24 -- "AP-5"

    ' セグメント情報
    rectangle "従業員用無線LAN\n(192.168.20.0/24)" as EmployeeLAN
    EmployeeLAN -- "AP-1"
    EmployeeLAN -- "AP-2"
    EmployeeLAN -- "AP-3"
    EmployeeLAN -- "AP-4"
    EmployeeLAN -- "AP-5"
    EmployeeLAN -- "執務室の業務PC"

    rectangle "来客用無線LAN\n(192.168.10.0/24)" as GuestLAN
    GuestLAN -- "AP-5"
    GuestLAN -- 来客持込端末
    GuestLAN -- プロジェクター
    GuestLAN -- 会議室の業務PC群1

    rectangle "サーバネットワーク\n(192.168.30.0/24)" as ServerLAN
    ServerLAN -- 業務サーバ
    ServerLAN -- DHCPサーバ
    ServerLAN -- DNSサーバ
    ServerLAN -- ディレクトリサーバ
}

@enduml
