<?php

return [
    0 => [
        'exam_code' => '2024_aki_1',
        'question_number' => 1,
        'sub_question_number' => 1,
        'small_question_number' => 0,
        'type' => 'input',
        'text' => '[暫定対策と追加調査の実施]について答えよ。
(1) 本文中及び図3中の[空欄 a]に入れる適切なホスト名を答えよ。',
        'options' => null,
        'max_length' => null,
    ],
    1 => [
        'exam_code' => '2024_aki_1',
        'question_number' => 1,
        'sub_question_number' => 2,
        'small_question_number' => 0,
        'type' => 'input',
        'text' => '(2) 本文中の[空欄 b]に入れる適切なホスト名を答えよ。',
        'options' => null,
        'max_length' => null,
    ],
    2 => [
        'exam_code' => '2024_aki_1',
        'question_number' => 1,
        'sub_question_number' => 3,
        'small_question_number' => 0,
        'type' => 'input',
        'text' => '(3) 本文中及び図3中の[空欄 c]に入れる適切なアカウント名を,表3の注記1に従って答えよ。',
        'options' => null,
        'max_length' => null,
    ],
    3 => [
        'exam_code' => '2024_aki_1',
        'question_number' => 1,
        'sub_question_number' => 4,
        'small_question_number' => 0,
        'type' => 'input',
        'text' => '(4) 図3中の[空欄 d]に入れる適切な対策を10字以内で答えよ。',
        'options' => null,
        'max_length' => '10',
    ],
    4 => [
        'exam_code' => '2024_aki_1',
        'question_number' => 1,
        'sub_question_number' => 5,
        'small_question_number' => 0,
        'type' => 'textarea',
        'text' => '(5) 図3中の下線①について,対策の内容を,具体的に答えよ。',
        'options' => null,
        'max_length' => null,
    ],
    5 => [
        'exam_code' => '2024_aki_1',
        'question_number' => 1,
        'sub_question_number' => 6,
        'small_question_number' => 0,
        'type' => 'textarea',
        'text' => '(6) 図3中の下線②について,調査の内容を,具体的に答えよ。',
        'options' => null,
        'max_length' => null,
    ],
    6 => [
        'exam_code' => '2024_aki_1',
        'question_number' => 1,
        'sub_question_number' => 7,
        'small_question_number' => 0,
        'type' => 'textarea',
        'text' => '(7) 本文中の下線③について,調査の内容を,具体的に答えよ。',
        'options' => null,
        'max_length' => null,
    ],
    7 => [
        'exam_code' => '2024_aki_1',
        'question_number' => 1,
        'sub_question_number' => 8,
        'small_question_number' => 1,
        'type' => 'textarea',
        'text' => '(8) 本文中の下線④について,検出する仕組みを,二つ答えよ。',
        'options' => [
            0 => [
                'label' => '1つ目',
                'value' => '1つ目',
            ],
        ],
        'max_length' => null,
    ],
    8 => [
        'exam_code' => '2024_aki_1',
        'question_number' => 1,
        'sub_question_number' => 8,
        'small_question_number' => 2,
        'type' => 'textarea',
        'text' => '',
        'options' => [
            0 => [
                'label' => '2つ目',
                'value' => '2つ目',
            ],
        ],
        'max_length' => null,
    ],
    9 => [
        'exam_code' => '2024_aki_1',
        'question_number' => 2,
        'sub_question_number' => 1,
        'small_question_number' => 1,
        'type' => 'input',
        'text' => '設問2 表6中の[空欄 e], [空欄 f]に入れる適切な字句を答えよ。',
        'options' => [
            0 => [
                'label' => '[e]',
                'value' => 'e',
            ],
        ],
        'max_length' => null,
    ],
    10 => [
        'exam_code' => '2024_aki_1',
        'question_number' => 2,
        'sub_question_number' => 1,
        'small_question_number' => 2,
        'type' => 'input',
        'text' => '',
        'options' => [
            0 => [
                'label' => '[f]',
                'value' => 'f',
            ],
        ],
        'max_length' => null,
    ],
];
