<?php

return [
    // 令和6年春問1
    [
        'year' => 2024,
        'season' => 'haru',
        'section' => 1,
        'question_number' => 1,
        'sub_question_number' => 1,
        'text' => "ステートレス",
    ],
    [
        'year' => 2024,
        'season' => 'haru',
        'section' => 1,
        'question_number' => 2,
        'sub_question_number' => 1,
        'text' => '500',
    ],
    [
        'year' => 2024,
        'season' => 'haru',
        'section' => 1,
        'question_number' => 2,
        'sub_question_number' => 2,
        'small_question_number' => 1,
        'text' => 'JWT ヘッダ内のalgに指定された値',
    ],
    [
        'year' => 2024,
        'season' => 'haru',
        'section' => 1,
        'question_number' => 2,
        'sub_question_number' => 2,
        'small_question_number' => 2,
        'text' => 'NONEでないことを検証する。',
    ],
    [
        'year' => 2024,
        'season' => 'haru',
        'section' => 1,
        'question_number' => 2,
        'sub_question_number' => 3,
        'text' => 'JWTに含まれる利用者IDがmidの値と一致するかどうかを検証する処理',
    ],
    [
        'year' => 2024,
        'season' => 'haru',
        'section' => 1,
        'question_number' => 2,
        'sub_question_number' => 4,
        'text' => '共通モジュール P',
    ],
    [
        'year' => 2024,
        'season' => 'haru',
        'section' => 1,
        'question_number' => 2,
        'sub_question_number' => 5,
        'text' => '連続失敗回数がしきい値を超えたらアカウントをロックする処理',
    ],
    [
        'year' => 2024,
        'season' => 'haru',
        'section' => 1,
        'question_number' => 3,
        'sub_question_number' => 1,
        'text' => 'テストサーバのindex.htmlへのアクセスを記録し,確認する仕組み',
    ],
    [
        'year' => 2024,
        'season' => 'haru',
        'section' => 1,
        'question_number' => 3,
        'sub_question_number' => 2,
        'small_question_number' => 1,
        'text' => 'Header',
    ],
    [
        'year' => 2024,
        'season' => 'haru',
        'section' => 1,
        'question_number' => 3,
        'sub_question_number' => 2,
        'small_question_number' => 2,
        'text' => 'Header',
    ],
    [
        'year' => 2024,
        'season' => 'haru',
        'section' => 1,
        'question_number' => 3,
        'sub_question_number' => 3,
        'text' => '¥W[jJ][nN][dD][iI]¥W または ¥W[jJ][nN][dD][iI]¥W',
    ],
    [
        'year' => 2024,
        'season' => 'haru',
        'section' => 1,
        'question_number' => 3,
        'sub_question_number' => 3,
        'small_question_number' => 1,
        'text' => '誤検知による遮断を防ぐことができる。',
    ],
    [
        'year' => 2024,
        'season' => 'haru',
        'section' => 1,
        'question_number' => 3,
        'sub_question_number' => 3,
        'small_question_number' => 2,
        'text' => 'アラートを受信したら攻撃かどうかを精査する。',
    ],
];
