name: CI

on:
    pull_request:
    push:
        branches: [ "main" ]
    
jobs:
    php:
        name: PHP (pint + phpunit)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  tools: composer
            
            - name: Install dependencies
              working-directory: src
              run: composer install --no-interaction --prefer-dist

            - name: Pint(check)
              working-directory: src
              run: vendor/bin/pint --test

            - name: PHPUnit
              working-directory: src
              env:
                APP_enV: testing
              run: php artisan test
            
    frontend:
        name: Frontend (tsc)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: "18"
                cache: "npm"
                cache-dependency-path: src/package-lock.json

            - name: Install deps
              working-directory: src
              run: npm ci
            
            - name: Typecheck
              working-directory: src
              run: npm run typecheck